from flaskproject import create_app, db
from flaskproject.models import Category, Product

app = create_app()
with app.app_context():
    # xóa bảng cũ và tạo lại nếu muốn làm sachk db
    # db.drop_all()

    db.create_all()

    # Kiểm tra nếu chưa có dữ liệu thì thêm
    if not Category.query.first():
        c1 = Category(name="iPhone")
        c2 = Category(name="iPad")
        c3 = Category(name="MacBook")
        db.session.add_all([c1, c2, c3])
        db.session.commit()

    if not Product.query.first():
        products = [
            {  # 1
                "name": "iPhone 17 Pro Max",
                "description": "",
                "price": 37000000,
                "screen": "6.9 inch với ProMotion lên đến 120Hz",
                "operating": "IOS 26",
                "camera_f": "18MP Center Stage",
                "camera_a": "48MP",
                "CPU": "Chip A19 Pro với GPU 6 lõi",
                "RAM": "12GB",
                "store": "256GB",
                "battery": "4252 mAh",
                "image": "img/products/iPhone_17_prm.jpg",
                "category_id": 1,
            },
            {  # 2
                "name": "iPad Pro",
                "description": "",
                "price": 29999000,
                "screen": "Màn hình Ultra Retina XDR, công nghệ ProMotion",
                "operating": "iPadOS 18",
                "camera_f": "Camera 12MP Center Stage trên cạnh ngang",
                "camera_a": "Camera 12MP Wide, Video 4K",
                "CPU": "Chip M5",
                "RAM": "12GB",
                "store": "256GB",
                "battery": "10340 mAh",
                "image": "img/products/iPadPro.jpg",
                "category_id": 2,
            },
            {  # 3
                "name": "MacBook Air 13'",
                "description": "",
                "price": 29000000,
                "screen": "Liquid Retina 13,6 inch",
                "operating": "macOS 15",
                "camera_f": "",
                "camera_a": "",
                "CPU": "Chip Apple M4",
                "RAM": "32GB",
                "store": "256GB",
                "battery": "4379 mAh",
                "image": "img/products/MacBookAir.jpg",
                "category_id": 3,
            },
            {  # 4
                "name": "iPhone Air",
                "description": "",
                "price": 31990000,
                "screen": "6,5 inch",
                "operating": "IOS 25",
                "camera_f": "18MP Center Stage",
                "camera_a": "48MP Fusion Main",
                "CPU": "Chip A19 Pro",
                "RAM": "12GB",
                "store": "128GB",
                "battery": "9705 mAh",
                "image": "img/products/iPhoneAir.jpg",
                "category_id": 1,
            },
            {  # 5
                "name": "iPhone 16e",
                "description": "",
                "price": 16999000,
                "screen": "Super Retina XDR 6,1 inch",
                "operating": "IOS 26",
                "camera_f": "18MP Center Stage",
                "camera_a": "Fusion 48MP Telephoto 2x",
                "CPU": "Chip A18, 4 lõi",
                "RAM": "12GB",
                "store": "256GB",
                "battery": "4005 mAh",
                "image": "img/products/iPhone16e.jpg",
                "category_id": 1,
            },
            {  # 6
                "name": "iPhone 16 Plus",
                "description": "",
                "price": 21999000,
                "screen": "6,7 inch",
                "operating": "IOS 26",
                "camera_f": "",
                "camera_a": "TrueDepth 12MP",
                "CPU": "Chip A18",
                "RAM": "12GB",
                "store": "256GB",
                "battery": "4674 mAh",
                "image": "img/products/iPhone16Plus.png",
                "category_id": 1,
            },
            {  # 7
                "name": "iPad Mini",
                "description": "",
                "price": 13744000,
                "screen": "Liquid Retina 8,3 inch với True Tone",
                "operating": "iPadOS 18",
                "camera_f": "",
                "camera_a": "TrueDepth 12MP",
                "CPU": "Chip A17 Pro, 6 lõi",
                "RAM": "12GB",
                "store": "256GB",
                "battery": "Thời lượng pin lên đến 26 giờ",
                "image": "img/products/iPadmini.jpg",
                "category_id": 2,
            },
            {  # 8
                "name": "iPad Air",
                "description": "",
                "price": 16689000,
                "screen": "Liquid Retina 11 inch",
                "operating": "iPadOS 18",
                "camera_f": "12MP Center Stage",
                "camera_a": "Wide 12MP",
                "CPU": "Chip Apple M3",
                "RAM": "16GB",
                "store": "128GB",
                "battery": "5013 mAh",
                "image": "img/products/iPadAir.jpg",
                "category_id": 2,
            },
            {  # 9
                "name": "MacBook Pro",
                "description": "",
                "price": 41999000,
                "screen": "Liquid Retina XDR",
                "operating": "macOS 15",
                "camera_f": "12MP Center Stage",
                "camera_a": "",
                "CPU": "Chip M5",
                "RAM": "32GB",
                "store": "2TB",
                "battery": "8700 mAh",
                "image": "img/products/MacBookPro.jpg",
                "category_id": 3,
            },
            {  # 10
                "name": "iPhone 17",
                "description": "",
                "price": 24999000,
                "screen": "Màn hình 6,3 inch với ProMotion lên đến 120Hz",
                "operating": "IOS 24",
                "camera_f": "18MP Center Stage",
                "camera_a": "48MP Dual Fusion",
                "CPU": "Chip A19 với GPU 5 lõi",
                "RAM": "16GB",
                "store": "512GB",
                "battery": "3692 mAh",
                "image": "img/products/iPhone17.jpg",
                "category_id": 1,
            },
            {  # 11
                "name": "iPhone 15",
                "description": "",
                "price": 17390000,
                "screen": "Màn hình 6,7 inch",
                "operating": "IOS 17",
                "camera_f": "12MP, ƒ/1.9",
                "camera_a": "Chính 48 MP & Phụ 12 MP",
                "CPU": "Chip A16 Bionic 6 nhân",
                "RAM": "6GB",
                "store": "128GB",
                "battery": "3349 mAh",
                "image": "img/products/iPhone15.jpg",
                "category_id": 1,
            },
            {  # 12
                "name": "iPhone 15",
                "description": "",
                "price": 25490000,
                "screen": "Màn hình 6,1 inch",
                "operating": "IOS 17",
                "camera_f": "12MP, ƒ/1.9",
                "camera_a": "Chính 48 MP, 24mm/f/1.78",
                "CPU": "Chip A17 Pro",
                "RAM": "",
                "store": "256GB",
                "battery": "4349 mAh",
                "image": "img/products/iPhone15prm.jpg",
                "category_id": 1,
            },
            {  # 13
                "name": "iPhone 15 Plus",
                "description": "",
                "price": 22590000,
                "screen": "Super Retina XDR, 6.7 inch",
                "operating": "IOS 17",
                "camera_f": "12MP",
                "camera_a": "Chính 48 MP, phụ 12 MP",
                "CPU": "Chip A16 Bionic",
                "RAM": "6GB",
                "store": "128GB",
                "battery": "4383 mAh, sạc 20W",
                "image": "img/products/iPhone15Plus.jpg",
                "category_id": 1,
            },
            {  # 14
                "name": "iPhone 13",
                "description": "",
                "price": 12490000,
                "screen": "Super Retina XDR, 6.7 inch",
                "operating": "IOS 16",
                "camera_f": "12MP",
                "camera_a": "2 camera 12 MP",
                "CPU": "Chip A15 Bionic",
                "RAM": "4GB",
                "store": "128GB",
                "battery": "3240 mAh, sạc 20W",
                "image": "img/products/iPhone13.jpg",
                "category_id": 1,
            },
            {  # 15
                "name": "iPhone 14",
                "description": "",
                "price": 13990000,
                "screen": "Super Retina XDR, 6.1 inch",
                "operating": "IOS 17",
                "camera_f": "12MP",
                "camera_a": "2 camera 12 MP",
                "CPU": "Chip A15 Bionic",
                "RAM": "6GB",
                "store": "128GB",
                "battery": "3279 mAh, sạc 20W",
                "image": "img/products/iPhone14.jpg",
                "category_id": 1,
            },
            {  # 16
                "name": "iPhone 16 Pro Max",
                "description": "",
                "price": 25590000,
                "screen": "Super Retina XDR, 6.3 inch",
                "operating": "IOS 23",
                "camera_f": "12MP",
                "camera_a": "Chính 48 MP & Phụ 48 MP, 12 MP",
                "CPU": "Chip A18 Pro 6 nhân",
                "RAM": "8GB",
                "store": "256GB",
                "battery": "27 giờ, sạc 20W",
                "image": "img/products/iPhone16prm.png",
                "category_id": 1,
            },
            {  # 17
                "name": "iPad A16 5G",
                "description": "",
                "price": 13890000,
                "screen": "Retina IPS LCD, 11 inch",
                "operating": "iPadOS 18",
                "camera_f": "12MP",
                "camera_a": "Chính 48 MP & Phụ 48 MP, 12 MP",
                "CPU": "Chip A16 5 nhân",
                "RAM": "5GB",
                "store": "256GB",
                "battery": "28.93 Wh, Sạc 20W",
                "image": "img/products/iPadA16_5G.jpg",
                "category_id": 2,
            },
            {  # 18
                "name": "iPad A16 5G",
                "description": "",
                "price": 20590000,
                "screen": "Retina IPS LCD, 11 inch",
                "operating": "iPadOS 18",
                "camera_f": "12MP",
                "camera_a": "Chính 48 MP & Phụ 48 MP, 12 MP",
                "CPU": "Chip Apple M3 8 nhân",
                "RAM": "8GB",
                "store": "128GB",
                "battery": "28.93 Wh, Sạc 20W",
                "image": "img/products/iPadAirM3_11inch.jpg",
                "category_id": 2,
            },
            {  # 19
                "name": "iPad Mini 7 5G",
                "description": "",
                "price": 17690000,
                "screen": "LED-backlit IPS LCD, 8.3 inch",
                "operating": "iPadOS 18",
                "camera_f": "12MP",
                "camera_a": "Chính 48 MP & Phụ 48 MP, 12 MP",
                "CPU": "Chip Apple A17 Pro 6",
                "RAM": "8GB",
                "store": "128GB",
                "battery": "19.3 Wh, Sạc 20W",
                "image": "img/products/iPadAirM3_11inch.jpg",
                "category_id": 2,
            },
            {  # 19
                "name": "iPad Mini 7 5G",
                "description": "",
                "price": 17690000,
                "screen": "LED-backlit IPS LCD, 8.3 inch",
                "operating": "iPadOS 18",
                "camera_f": "12MP",
                "camera_a": "Chính 48 MP & Phụ 48 MP, 12 MP",
                "CPU": "Chip Apple A17 Pro 6",
                "RAM": "8GB",
                "store": "128GB",
                "battery": "19.3 Wh, Sạc 20W",
                "image": "img/products/iPadAirM3_11inch.jpg",
                "category_id": 2,
            },
            {  # 20
                "name": "MacBook Air 13 inch M4",
                "description": "",
                "price": 25290000,
                "screen": "13.6 inch, Liquid Retina (2560 x 1664)",
                "operating": "macOS 15",
                "camera_f": "12MP",
                "camera_a": "",
                "CPU": "Apple M4, 8 nhân GPU",
                "RAM": "16GB",
                "store": "256GB",
                "battery": "",
                "image": "img/products/MacBook Air 13 inch M4.jpg",
                "category_id": 3,
            },
            {  # 21
                "name": "MacBook Air 13 inch M2",
                "description": "",
                "price": 19890000,
                "screen": "13.6 inch, Liquid Retina (2560 x 1664)",
                "operating": "macOS 15",
                "camera_f": "12MP",
                "camera_a": "",
                "CPU": "Apple M2, 8 nhân GPU",
                "RAM": "16GB",
                "store": "256GB",
                "battery": "",
                "image": "img/products/MacBook Air 13 inch M2.jpg",
                "category_id": 3,
            },
            {  # 22
                "name": "MacBook Pro 16 inch M4 Pro",
                "description": "",
                "price": 65590000,
                "screen": "16.2 inch, Liquid Retina XDR display, 120Hz",
                "operating": "macOS 15",
                "camera_f": "14MP",
                "camera_a": "",
                "CPU": "Apple M4 Pro, 20 nhân GPU",
                "RAM": "24GB",
                "store": "512GB",
                "battery": "",
                "image": "img/products/MacBook Pro 16 inch M4 Pro.jpg",
                "category_id": 3,
            },
        ]
        for p in products:
            product = Product(**p)
            db.session.add(product)
        db.session.commit()

    print("✅ Database initialized with sample data!")
