"""Them cot moi vao Receipt, Product

Revision ID: 4a0bb156fa84
Revises: 55e6ccfdb5dc
Create Date: 2025-11-08 23:52:19.248936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0bb156fa84'
down_revision = '55e6ccfdb5dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_quantity', sa.Integer(), nullable=False))

    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('shipping_phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('shipping_address', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('shipping_phone')
        batch_op.drop_column('customer_name')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('stock_quantity')

    # ### end Alembic commands ###
