"""Add status column to Receipt

Revision ID: 55e6ccfdb5dc
Revises: 737127fb22fc
Create Date: 2025-11-08 23:26:56.376897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e6ccfdb5dc'
down_revision = '737127fb22fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
