"""Add total_price to Receipt

Revision ID: 737127fb22fc
Revises: 
Create Date: 2025-11-08 22:23:50.587498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737127fb22fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
